name: Render MIDI → MP3

on:
  push:
    paths:
      - 'midi/**'
      - 'render_midi.py'
      - '.github/workflows/render_midi.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fluidsynth ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python libraries
        run: |
          pip install midi2audio

      - name: Render MIDI to MP3
        env:
          SOUND_FONT: ./GameBoy.sf2
          MIDI_DIR:    ./midi
          OUTPUT_DIR:  ./output
        run: |
          python render_midi.py

      - name: Debug
        run: |
          echo "=== output directory ==="
          ls -lh output || echo "output not found"

      - name: Upload MP3 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: midi-mp3
          path: output

      - name: Commit generated MP3s back to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🔉 Add generated MP3 files"
          file_pattern: output/*.mp3
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
